### ISSUE TITLE
Flaky integration tests due not waiting for long running operations

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/signify-ts#201]
I found a couple of times that there are some timing errors in the tests.

For example, in some places we do code like:

```js
const icp = await identifiers().create(aid)
await waitOperation(await icp.op())

// This returns a long running operation that is not waited for.
await addEndRole(aid)

// Here, oobis will not contain any agent oobis unless the long running operation for adding the end role has completed.
const oobis = await getOobi(aid, role=agent)

// => which means that these type of calls will fail.
await resolveOobi(oobis[0])
```

In a lot of the tests, we have started using the getOrCreateIdentifier function from test-setup.ts which does that.

Here is an example of a failed test run: https://github.com/WebOfTrust/signify-ts/actions/runs/7633782513/job/20796640953

```
    console.log
      Member1 resolved 4 OOBIs

      at Object.run (multisig.test.ts:56:13)

  ● multisig

    {"title": "400 Bad Request", "description": "invalid OOBI request body, either 'rpy' or 'url' is required"}

      211 |         if (!res.ok) {
      212 |             const error = await res.text();
    > 213 |             throw new Error(error);
          |                   ^
      214 |         }
      215 |         const isSameAgent =
      216 |             this.agent?.pre === res.headers.get('signify-resource');

      at SignifyClient.fetch (../../src/keri/app/clienting.ts:213:19)
      at async Oobis.resolve (../../src/keri/app/coring.ts:58:21)
      at async Object.run (multisig.test.ts:58:15)
   ```

**Comment by lenkan** [comment]
Fixed by #210
